'use client';

import { useMemo } from 'react';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip as ChartTooltip } from 'recharts';
import { Box, Chip, Paper, Stack, Typography } from '@mui/material';
import { deleteCompany, saveCompany } from '../lib/firebase/companies-service';
import { deleteLine, saveLine } from '../lib/firebase/lines-service';
import { deleteOperator, saveOperator } from '../lib/firebase/operators-service';
import { deleteProblem, saveProblem } from '../lib/firebase/problems-service';
import { deleteUser, saveUser } from '../lib/firebase/users-service';
import { deleteManagedStorageUrl } from '../lib/firebase/storage-service';
import { useActiveCompany } from '../hooks/active-company-context';
import type { Company, DeviceToken, FactoryCall, Operator, PortalUser, Problem, ProductionLine } from '../types/firebase-models';
import { RecordManagementModule, type ManagedField } from './record-management-module';
import { DetailedRecordModule, type DetailField } from './detailed-record-module';

const companyFields: ManagedField<Company>[] = [{ key: 'name', label: 'Pavadinimas', required: true }, { key: 'companyCode', label: 'Kodas' }, { key: 'city', label: 'Miestas' }, { key: 'manager', label: 'Atsakingas asmuo' }, { key: 'email', label: 'El. paštas', type: 'email' }, { key: 'phone', label: 'Telefonas' }, { key: 'logoUrl', label: 'Logotipo URL' }];
const userFields: ManagedField<PortalUser>[] = [{ key: 'name', label: 'Vardas' }, { key: 'email', label: 'El. paštas', type: 'email' }, { key: 'role', label: 'Rolė', required: true }, { key: 'companyId', label: 'companyId' }];
const dateTime = (value?: string | number) => { const time = Number(value ?? 0); return Number.isFinite(time) && time > 0 ? new Date(time).toLocaleString('lt-LT') : '—'; };
const operatorDetailFields: DetailField<Operator>[] = [{ key: 'name', label: 'Vardas', required: true }, { key: 'email', label: 'El. paštas', type: 'email' }, { key: 'phone', label: 'Telefonas' }, { key: 'department', label: 'Atsakomybė / padalinys' }, { key: 'shift', label: 'Pamaina' }, { key: 'lineId', label: 'Linija' }, { key: 'companyId', label: 'companyId' }, { key: 'active', label: 'Aktyvus', type: 'boolean' }];
const administratorDetailFields: DetailField<PortalUser>[] = [{ key: 'name', label: 'Vardas' }, { key: 'email', label: 'El. paštas', type: 'email' }, { key: 'role', label: 'Rolė', options: ['admin', 'administrator', 'manager', 'vadovas'] }, { key: 'companyId', label: 'companyId' }];
const lineDetailFields: DetailField<ProductionLine>[] = [{ key: 'name', label: 'Pavadinimas', required: true }, { key: 'code', label: 'Kodas' }, { key: 'companyId', label: 'companyId' }, { key: 'zone', label: 'Gamybos zona' }, { key: 'technicians', label: 'Priskirti technikai', multiline: true }, { key: 'active', label: 'Aktyvi', type: 'boolean' }];
const problemDetailFields: DetailField<Problem>[] = [{ key: 'name', label: 'Pavadinimas', required: true }, { key: 'code', label: 'Kodas' }, { key: 'category', label: 'Kategorija' }, { key: 'priority', label: 'Prioritetas', options: ['Žemas', 'Vidutinis', 'Aukštas', 'Kritinis'] }, { key: 'sla', label: 'SLA' }, { key: 'color', label: 'Spalva', type: 'color' }, { key: 'description', label: 'Aprašymas', multiline: true }, { key: 'active', label: 'Aktyvus', type: 'boolean' }];

export function CompaniesManagementModule() { const { companies } = useActiveCompany(); return <RecordManagementModule title="Įmonės informacija" description="Įmonių duomenys realiu laiku" items={companies} fields={companyFields} save={saveCompany} remove={async id => { const company = companies.find(item => item.id === id); await deleteManagedStorageUrl(company?.logoUrl); await deleteCompany(id); }} removeMessage={item => `Ar tikrai norite pašalinti „${item.name || item.id}“? Valdomas logotipas taip pat bus pašalintas.`} emptyLabel="Įmonių nėra." />; }
export function OperatorsManagementModule({ operators, users, calls }: { operators: Operator[]; users: PortalUser[]; calls: FactoryCall[] }) { return <DetailedRecordModule title="Operatoriai" description="Operatorių duomenys ir sukurtų iškvietimų apkrova realiu laiku" items={operators} fields={operatorDetailFields} columns={[{ label: 'Vardas', value: item => item.name || item.email || item.id }, { label: 'El. paštas', value: item => item.email || '—' }, { label: 'Būsena', value: item => <Chip size="small" label={item.active === false ? 'Neaktyvus' : 'Aktyvus'} color={item.active === false ? 'default' : 'success'} /> }, { label: 'Atsakomybė', value: item => item.department || '—' }, { label: 'Paskutinis prisijungimas', value: item => dateTime(item.lastLoginTime ?? item.lastLogin ?? users.find(user => user.id === item.id || user.email === item.email)?.lastLoginTime) }, { label: 'Sukurti iškvietimai', value: item => calls.filter(call => call.operatorId === item.id || call.operator === item.name || call.operator === item.email).length }]} createDefaults={{ active: true } as Partial<Operator>} save={saveOperator} remove={deleteOperator} details={item => <Paper variant="outlined" sx={{ p: 1.5, borderColor: 'divider' }}><Typography variant="subtitle2">Visa informacija</Typography><Typography variant="body2" color="text.secondary" mt={0.5}>Firebase UID: {item.uid || item.id || '—'}</Typography><Typography variant="body2" color="text.secondary">Paskutinis prisijungimas: {dateTime(item.lastLoginTime ?? item.lastLogin)}</Typography></Paper>} />; }
export function LinesManagementModule({ lines, technicians }: { lines: ProductionLine[]; technicians: { id?: string; name?: string }[] }) { return <DetailedRecordModule title="Linijos" description="Gamybos zonos, aktyvumas ir priskirti technikai realiu laiku" items={lines} fields={lineDetailFields} columns={[{ label: 'Pavadinimas', value: item => item.name || item.id }, { label: 'Kodas', value: item => item.code || '—' }, { label: 'Zona', value: item => item.zone || '—' }, { label: 'Technikai', value: item => item.technicians?.join(', ') || item.technicianIds?.map(id => technicians.find(tech => tech.id === id)?.name || id).join(', ') || '—' }, { label: 'Būsena', value: item => <Chip size="small" label={item.active === false ? 'Neaktyvi' : 'Aktyvi'} color={item.active === false ? 'default' : 'success'} /> }]} createDefaults={{ active: true } as Partial<ProductionLine>} save={saveLine} remove={deleteLine} />; }
export function ProblemsManagementModule({ problems }: { problems: Problem[] }) { return <DetailedRecordModule title="Gedimų tipai" description="Prioritetai, SLA ir spalviniai žymėjimai realiu laiku" items={problems} fields={problemDetailFields} columns={[{ label: 'Pavadinimas', value: item => item.name || item.id }, { label: 'Kategorija', value: item => item.category || '—' }, { label: 'Prioritetas', value: item => item.priority || '—' }, { label: 'SLA', value: item => item.sla || '—' }, { label: 'Spalva', value: item => item.color ? <Box sx={{ width: 18, height: 18, borderRadius: '50%', bgcolor: item.color, border: '1px solid #607089' }} /> : '—' }, { label: 'Būsena', value: item => <Chip size="small" label={item.active === false ? 'Neaktyvus' : 'Aktyvus'} color={item.active === false ? 'default' : 'success'} /> }]} createDefaults={{ active: true, priority: 'Vidutinis' } as Partial<Problem>} save={saveProblem} remove={deleteProblem} />; }
export function AdministratorsModule({ users }: { users: PortalUser[] }) { return <DetailedRecordModule title="Administratoriai" description="Administratorių paskyros, rolės ir įmonės prieiga realiu laiku" items={users} fields={administratorDetailFields} columns={[{ label: 'Vardas', value: item => item.name || item.email || item.id }, { label: 'El. paštas', value: item => item.email || '—' }, { label: 'Rolė', value: item => item.role || '—' }, { label: 'companyId', value: item => item.companyId || '—' }, { label: 'Paskutinis prisijungimas', value: item => dateTime(item.lastLoginTime ?? item.lastLogin) }]} filter={item => ['admin', 'administrator'].includes(String(item.role ?? '').toLowerCase())} createDefaults={{ role: 'admin' } as Partial<PortalUser>} save={saveUser} remove={deleteUser} details={item => <Paper variant="outlined" sx={{ p: 1.5, borderColor: 'divider' }}><Typography variant="subtitle2">Paskyros informacija</Typography><Typography variant="body2" color="text.secondary" mt={0.5}>Firebase UID: {item.uid || item.id || '—'}</Typography><Typography variant="body2" color="text.secondary">Prisijungęs: {item.online ? 'Taip' : 'Ne'}</Typography></Paper>} />; }
export function RolesPermissionsModule({ users }: { users: PortalUser[] }) { return <RecordManagementModule title="Rolės ir teisės" description="Vartotojų rolės ir įmonės prieiga" items={users} fields={userFields} createDefaults={{ role: 'operatorius' } as Partial<PortalUser>} save={saveUser} remove={deleteUser} emptyLabel="Vartotojų nėra." />; }

export function FcmDiagnosticsModule({ tokens, users }: { tokens: DeviceToken[]; users: PortalUser[] }) {
  const rows = useMemo(() => tokens.map(token => ({ token, user: users.find(user => user.id === token.userId || user.uid === token.userId) })), [tokens, users]);
  return <><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ md: 'center' }} spacing={2} mb={3}><Box><Typography variant="h4">FCM diagnostika</Typography><Typography variant="body2" color="text.secondary" mt={0.5}>Tik skaitymui: klientų registruoti įrenginiai iš /tokens</Typography></Box><Chip color="primary" variant="outlined" label={`${tokens.length} tokenai`} /></Stack><Paper sx={{ border: '1px solid #293342', overflow: 'hidden' }}><Box sx={{ overflowX: 'auto' }}><table style={{ width: '100%', minWidth: 720, borderCollapse: 'collapse' }}><thead><tr>{['Įrenginio ID', 'Vartotojas', 'El. paštas', 'Atnaujinta', 'Būsena'].map(header => <th key={header} style={{ textAlign: 'left', padding: 14, color: '#8f9cad', fontSize: 13 }}>{header}</th>)}</tr></thead><tbody>{rows.map(({ token, user }) => <tr key={token.id}><td style={{ padding: 14, borderTop: '1px solid #293342' }}>{token.id}</td><td style={{ padding: 14, borderTop: '1px solid #293342' }}>{user?.name || token.userId || '—'}</td><td style={{ padding: 14, borderTop: '1px solid #293342' }}>{user?.email || '—'}</td><td style={{ padding: 14, borderTop: '1px solid #293342' }}>{token.updatedAt ? new Date(Number(token.updatedAt)).toLocaleString('lt-LT') : '—'}</td><td style={{ padding: 14, borderTop: '1px solid #293342' }}><Chip size="small" color="success" label="Registruotas" /></td></tr>)}</tbody></table>{!rows.length && <Typography p={6} textAlign="center" color="text.secondary">Registruotų FCM įrenginių nėra.</Typography>}</Box></Paper></>;
}

export function StatisticsModule({ calls, technicians, operators }: { calls: FactoryCall[]; technicians: unknown[]; operators: unknown[] }) {
  const data = useMemo(() => { const count = (values: string[]) => calls.filter(call => values.includes(String(call.status ?? '').toLowerCase())).length; return [{ name: 'Laukia', value: count(['waiting', 'naujas']), color: '#ffb54c' }, { name: 'Vykdomi', value: count(['repairing', 'vykdomas', 'accepted', 'priskirtas']), color: '#4b9cff' }, { name: 'Užbaigti', value: count(['completed', 'užbaigtas', 'uždarytas']), color: '#38d996' }]; }, [calls]);
  return <><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ md: 'center' }} spacing={2} mb={3}><Box><Typography variant="h4">Statistika</Typography><Typography variant="body2" color="text.secondary" mt={0.5}>Realių iškvietimų ir komandos duomenų suvestinė</Typography></Box></Stack><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' }, gap: 2.5, mb: 2.5 }}><Paper sx={{ p: 2.5, border: '1px solid #293342' }}><Typography color="text.secondary">Visi iškvietimai</Typography><Typography variant="h4" mt={1}>{calls.length}</Typography></Paper><Paper sx={{ p: 2.5, border: '1px solid #293342' }}><Typography color="text.secondary">Technikai</Typography><Typography variant="h4" mt={1}>{technicians.length}</Typography></Paper><Paper sx={{ p: 2.5, border: '1px solid #293342' }}><Typography color="text.secondary">Operatoriai</Typography><Typography variant="h4" mt={1}>{operators.length}</Typography></Paper></Box><Paper sx={{ p: 2.5, border: '1px solid #293342', height: 340 }}><Typography fontWeight={700}>Iškvietimų būsenos</Typography><ResponsiveContainer width="100%" height="90%"><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={65} outerRadius={105}>{data.map(item => <Cell key={item.name} fill={item.color} />)}</Pie><ChartTooltip /></PieChart></ResponsiveContainer></Paper></>;
}
